"""CEG-WM model runtime boundary.

runtime_configuration_and_adapter exposes frozen identity/lifecycle control. content_write_and_vae adds paired content
materialization measurements and deterministic VAE boundaries. qk_observation adds
image-only registered-layer Q/K capture. Method semantics remain in ``main``.
"""

from .adapter import (
    RuntimeAdapterError,
    RuntimeAdapterState,
    RuntimeExecutionIdentity,
    RuntimeSession,
    Sd35RuntimeAdapter,
    create_runtime_adapter,
    select_runtime_device,
)
from .backend import (
    GenerationCallback,
    RuntimeBackend,
    RuntimeBackendError,
    RuntimeBackendIdentity,
    RuntimeContentBackend,
    RuntimeDetectionConditioning,
    RuntimeDetectionScheduleStep,
    RuntimeDeviceCapabilities,
    RuntimeDifferentiableQkBackend,
    RuntimeGenerationPromptIdentity,
    RuntimeGenerationSuffixBackend,
    RuntimeGenerationSuffixContext,
    RuntimeGenerationWithSuffixContextResult,
    RuntimeGeometrySynchronizationBackend,
    RuntimeQkBackend,
    RuntimeQkForwardIdentity,
    RuntimeVaeBackend,
    RuntimeVaeFactors,
    RuntimeVaePosterior,
)
from .configuration import (
    DEFAULT_RUNTIME_CONFIG_PATH,
    RUNTIME_CANDIDATE_ID,
    RuntimeConfigurationError,
    RuntimeDependencyLock,
    Sd35RuntimeConfiguration,
    load_runtime_configuration,
    parse_runtime_configuration,
)
from .content_write import (
    CleanImageVaeObservationResult,
    ContentEmbeddingOperation,
    SalientLocalLfEmbeddingOperation,
    ContentWriteGeometrySuffixResult,
    ContentMaterializationAttempt,
    ContentMaterializationMeasurement,
    ContentWriteVaeResult,
    RuntimeContentExecutionError,
    SalientLocalLfContentWriteResult,
    SalientLocalLfDetectionObservationResult,
    execute_clean_image_and_vae_observation,
    execute_content_write_and_capture_geometry_suffix,
    execute_salient_local_lf_content_write_and_vae,
    measure_content_materialization,
    observe_salient_local_lf_detection_image,
)
from .geometry_synchronization import (
    RuntimeActualQkSuffixResult,
    RuntimeDifferentiableQkSuffixResult,
    RuntimeGeometrySynchronizationError,
    materialize_geometry_candidate,
    observe_actual_qk_from_generation_suffix,
    observe_differentiable_qk_from_generation_suffix,
)
from .inspyrenet_saliency import (
    INSPYRENET_CHECKPOINT_ASSET_BASENAME,
    INSPYRENET_CHECKPOINT_ASSET_IDENTITY,
    INSPYRENET_CHECKPOINT_SHA256,
    INSPYRENET_CHECKPOINT_SIZE,
    INSPYRENET_PREPROCESS_SPATIAL_SIZE,
    InspyrenetSaliencyRuntime,
    InspyrenetSaliencyRuntimeError,
)
from .qk_observation import (
    RuntimeQkObservationError,
    RuntimeQkObservationResult,
    observe_detection_qk,
    observe_differentiable_detection_qk,
)
from .routing_observation import (
    ROUTING_OBSERVATION_CANDIDATE_ID,
    ROUTING_PROBE_RELATIVE_STEP,
    RuntimeRoutingObservationError,
    RuntimeRoutingObservationResult,
    RuntimeRoutingReferenceMeasurement,
    measure_generation_routing_reference_inputs,
    normalize_generation_routing_measurement,
    observe_generation_routing,
)
from .sd35_backend import (
    Sd35BackendError,
    Sd35PipelineBackend,
)

__all__ = [
    "DEFAULT_RUNTIME_CONFIG_PATH",
    "INSPYRENET_CHECKPOINT_ASSET_BASENAME",
    "INSPYRENET_CHECKPOINT_ASSET_IDENTITY",
    "INSPYRENET_CHECKPOINT_SHA256",
    "INSPYRENET_CHECKPOINT_SIZE",
    "INSPYRENET_PREPROCESS_SPATIAL_SIZE",
    "CleanImageVaeObservationResult",
    "ContentEmbeddingOperation",
    "SalientLocalLfEmbeddingOperation",
    "ContentWriteGeometrySuffixResult",
    "ContentMaterializationAttempt",
    "ContentMaterializationMeasurement",
    "ContentWriteVaeResult",
    "GenerationCallback",
    "InspyrenetSaliencyRuntime",
    "InspyrenetSaliencyRuntimeError",
    "RUNTIME_CANDIDATE_ID",
    "RuntimeAdapterError",
    "RuntimeAdapterState",
    "RuntimeBackend",
    "RuntimeBackendError",
    "RuntimeBackendIdentity",
    "RuntimeContentBackend",
    "RuntimeContentExecutionError",
    "SalientLocalLfContentWriteResult",
    "SalientLocalLfDetectionObservationResult",
    "RuntimeConfigurationError",
    "RuntimeDetectionConditioning",
    "RuntimeDetectionScheduleStep",
    "RuntimeDependencyLock",
    "RuntimeDeviceCapabilities",
    "RuntimeDifferentiableQkBackend",
    "RuntimeGenerationPromptIdentity",
    "RuntimeGenerationSuffixBackend",
    "RuntimeGenerationSuffixContext",
    "RuntimeGenerationWithSuffixContextResult",
    "RuntimeGeometrySynchronizationBackend",
    "RuntimeGeometrySynchronizationError",
    "RuntimeExecutionIdentity",
    "RuntimeQkBackend",
    "RuntimeQkForwardIdentity",
    "RuntimeQkObservationError",
    "RuntimeQkObservationResult",
    "RuntimeActualQkSuffixResult",
    "RuntimeDifferentiableQkSuffixResult",
    "RuntimeRoutingObservationError",
    "RuntimeRoutingObservationResult",
    "RuntimeRoutingReferenceMeasurement",
    "RuntimeSession",
    "RuntimeVaeBackend",
    "RuntimeVaeFactors",
    "RuntimeVaePosterior",
    "Sd35RuntimeAdapter",
    "Sd35RuntimeConfiguration",
    "ROUTING_OBSERVATION_CANDIDATE_ID",
    "ROUTING_PROBE_RELATIVE_STEP",
    "Sd35BackendError",
    "Sd35PipelineBackend",
    "create_runtime_adapter",
    "execute_clean_image_and_vae_observation",
    "execute_content_write_and_capture_geometry_suffix",
    "execute_salient_local_lf_content_write_and_vae",
    "load_runtime_configuration",
    "measure_content_materialization",
    "materialize_geometry_candidate",
    "measure_generation_routing_reference_inputs",
    "normalize_generation_routing_measurement",
    "observe_detection_qk",
    "observe_differentiable_detection_qk",
    "observe_actual_qk_from_generation_suffix",
    "observe_differentiable_qk_from_generation_suffix",
    "observe_generation_routing",
    "observe_salient_local_lf_detection_image",
    "parse_runtime_configuration",
    "select_runtime_device",
]
