"""Geometry-V2 keyed neural corner synchronization contracts."""

from cegwm.geometry_v2.contracts import (
    CANONICAL_CORNERS,
    ContentDetectorIdentity,
    GEOMETRY_AUTHORITY,
    GEOMETRY_KEY_DOMAIN,
    GeometryEstimate,
    KeyedSyncTarget,
    METHOD_IDENTITY,
    PROTOCOL_IDENTITY,
    RectificationRequest,
    ReliabilityAssessment,
    ReliabilityPolicy,
    assert_content_detector_identity_preserved,
    assess_reliability,
    build_rectification_request,
    derive_keyed_sync_target,
)
from cegwm.geometry_v2.neural_sync import (
    BlindCornerExtractor,
    CornerPrediction,
    EmbeddedBatch,
    IMAGE_SIZE,
    KeyedResidualEmbedder,
    MAX_RESIDUAL,
    n0_joint_loss,
)
from cegwm.geometry_v2.operational import (
    ATTACKS,
    CONFIRMATION_UNIT_COUNT,
    N0RunResult,
    apply_pillow_attack,
    decide_n0_status,
    package_n0,
    run_n0,
)

__all__ = [
    "CANONICAL_CORNERS",
    "ATTACKS",
    "BlindCornerExtractor",
    "CONFIRMATION_UNIT_COUNT",
    "ContentDetectorIdentity",
    "CornerPrediction",
    "EmbeddedBatch",
    "GEOMETRY_AUTHORITY",
    "GEOMETRY_KEY_DOMAIN",
    "GeometryEstimate",
    "IMAGE_SIZE",
    "KeyedResidualEmbedder",
    "KeyedSyncTarget",
    "MAX_RESIDUAL",
    "METHOD_IDENTITY",
    "N0RunResult",
    "PROTOCOL_IDENTITY",
    "RectificationRequest",
    "ReliabilityAssessment",
    "ReliabilityPolicy",
    "assert_content_detector_identity_preserved",
    "assess_reliability",
    "apply_pillow_attack",
    "build_rectification_request",
    "decide_n0_status",
    "derive_keyed_sync_target",
    "n0_joint_loss",
    "package_n0",
    "run_n0",
]
